version: '3'
services:
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      APP_HOST: localhost
      APP_PORT: 8080
      DB_HOST: redis
      DB_PORT: 6379
    depends_on:
      - redis
  redis:
    image: redis:5.0.5
    ports:
      - 6379:6379
